//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationAccessInfo
    {
        public long ApplicationAccessInfoId { get; set; }
        public Nullable<int> AttendeeId { get; set; }
        public Nullable<System.DateTime> ApplicationStartTime { get; set; }
        public Nullable<System.DateTime> ApplicationEndTime { get; set; }
    }
}
