//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attende
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attende()
        {
            this.AttendeeGroups = new HashSet<AttendeeGroup>();
            this.AttendesEvents = new HashSet<AttendesEvent>();
            this.BookMarks = new HashSet<BookMark>();
            this.ChannelUsers = new HashSet<ChannelUser>();
            this.DocumentFavourites = new HashSet<DocumentFavourite>();
            this.ForumSocialComments = new HashSet<ForumSocialComment>();
            this.ForumSocialComments1 = new HashSet<ForumSocialComment>();
            this.ManagerEvents = new HashSet<ManagerEvent>();
            this.Messagings = new HashSet<Messaging>();
            this.Messagings1 = new HashSet<Messaging>();
            this.Notes = new HashSet<Note>();
            this.PhotoLikes = new HashSet<PhotoLike>();
            this.PostUserLikes = new HashSet<PostUserLike>();
            this.PostUserLikes1 = new HashSet<PostUserLike>();
            this.QRHistories = new HashSet<QRHistory>();
            this.QRHistories1 = new HashSet<QRHistory>();
            this.SocialForums = new HashSet<SocialForum>();
            this.SocialForums1 = new HashSet<SocialForum>();
            this.Sys_Log = new HashSet<Sys_Log>();
            this.TextChats = new HashSet<TextChat>();
            this.TextChats1 = new HashSet<TextChat>();
            this.UserSessions = new HashSet<UserSession>();
            this.UserSessions1 = new HashSet<UserSession>();
            this.Documents = new HashSet<Document>();
            this.UserNotifications = new HashSet<UserNotification>();
            this.Responses = new HashSet<Response>();
            this.SurveySubmittedFors = new HashSet<SurveySubmittedFor>();
            this.SocialCommentLikes = new HashSet<SocialCommentLike>();
            this.QRCodes = new HashSet<QRCode>();
            this.PhotoLikes1 = new HashSet<PhotoLike1>();
            this.AppDownloads = new HashSet<AppDownload>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string InstagramURL { get; set; }
        public Nullable<System.DateTime> AddedON { get; set; }
        public Nullable<int> AddedBY { get; set; }
        public bool Status { get; set; }
        public string DeviceToken { get; set; }
        public string Email { get; set; }
        public string LinkedinURL { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<System.DateTime> codeDate { get; set; }
        public string Unique_Participant_ID { get; set; }
        public Nullable<bool> Imageapprove { get; set; }
        public string RequestedImage { get; set; }
        public string CompanyName { get; set; }
        public string TitleName { get; set; }
        public string Website { get; set; }
        public bool IsSpeaker { get; set; }
        public bool EnableMessaging { get; set; }
        public Nullable<bool> EnableAlertEmails { get; set; }
        public Nullable<bool> EnableAttendeeMessagingEmails { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsUploadedImage { get; set; }
    
        public virtual AdminInfo AdminInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendeeGroup> AttendeeGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendesEvent> AttendesEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookMark> BookMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelUser> ChannelUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentFavourite> DocumentFavourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumSocialComment> ForumSocialComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumSocialComment> ForumSocialComments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerEvent> ManagerEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messaging> Messagings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messaging> Messagings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoLike> PhotoLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostUserLike> PostUserLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostUserLike> PostUserLikes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRHistory> QRHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRHistory> QRHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialForum> SocialForums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialForum> SocialForums1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Log> Sys_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextChat> TextChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextChat> TextChats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotification> UserNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response> Responses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveySubmittedFor> SurveySubmittedFors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialCommentLike> SocialCommentLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCode> QRCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoLike1> PhotoLikes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppDownload> AppDownloads { get; set; }
    }
}
