//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelUser
    {
        public int ID { get; set; }
        public int ChannelID { get; set; }
        public Nullable<int> AttendeeID { get; set; }
        public string MemberSID { get; set; }
    
        public virtual Attende Attende { get; set; }
        public virtual ChatChannel ChatChannel { get; set; }
    }
}
