//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class channel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public channel()
        {
            this.UserChannelUnreadCounts = new HashSet<UserChannelUnreadCount>();
            this.UserChatChannels = new HashSet<UserChatChannel>();
            this.channelmessages = new HashSet<channelmessage>();
        }
    
        public int channelid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isGroup { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GroupImage { get; set; }
    
        public virtual channelgroup channelgroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserChannelUnreadCount> UserChannelUnreadCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserChatChannel> UserChatChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<channelmessage> channelmessages { get; set; }
        public virtual GroupInfo GroupInfo { get; set; }
    }
}
