//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class channelgroup
    {
        public int channelid { get; set; }
        public string groupname { get; set; }
        public int groupadminid { get; set; }
        public string groupimage { get; set; }
    
        public virtual channel channel { get; set; }
    }
}
