//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelMessage1
    {
        public long id { get; set; }
        public int channelid { get; set; }
        public int userid { get; set; }
        public string message { get; set; }
        public System.DateTime sentdate { get; set; }
        public Nullable<byte> messagetype { get; set; }
        public string type { get; set; }
    
        public virtual Channel1 Channel { get; set; }
    }
}
