//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Activites = new HashSet<Activite>();
            this.AttendesEvents = new HashSet<AttendesEvent>();
            this.ChatChannels = new HashSet<ChatChannel>();
            this.Documents = new HashSet<Document>();
            this.EventLocationDetails = new HashSet<EventLocationDetail>();
            this.FloorMapLocations = new HashSet<FloorMapLocation>();
            this.FloorMappings = new HashSet<FloorMapping>();
            this.FloorRegionMappings = new HashSet<FloorRegionMapping>();
            this.FloorRegionMappings1 = new HashSet<FloorRegionMapping>();
            this.GroupInfoes = new HashSet<GroupInfo>();
            this.Notifications = new HashSet<Notification>();
            this.PhotoAlbums = new HashSet<PhotoAlbum>();
            this.Photos = new HashSet<Photo>();
            this.QRCodes = new HashSet<QRCode>();
            this.QRCodes1 = new HashSet<QRCode>();
            this.SocialForums = new HashSet<SocialForum>();
            this.SocialForums1 = new HashSet<SocialForum>();
            this.SponsorsEvents = new HashSet<SponsorsEvent>();
            this.Themes = new HashSet<Theme>();
            this.WidgetMappings = new HashSet<WidgetMapping>();
            this.ExhibitorsEvents = new HashSet<ExhibitorsEvent>();
            this.VendorsEvents = new HashSet<VendorsEvent>();
            this.Notes = new HashSet<Note>();
            this.SurveySubmittedFors = new HashSet<SurveySubmittedFor>();
            this.WaiverFormTemplateMappings = new HashSet<WaiverFormTemplateMapping>();
            this.EventVideos = new HashSet<EventVideo>();
            this.EventInformations = new HashSet<EventInformation>();
            this.userchannels = new HashSet<userchannel>();
            this.UserChatChannels = new HashSet<UserChatChannel>();
        }
    
        public int ID { get; set; }
        public bool ModeratePost { get; set; }
        public Nullable<int> GalacticEventId { get; set; }
        public string EventName { get; set; }
        public string Message { get; set; }
        public bool EnableThemes { get; set; }
        public bool EnableQrCode { get; set; }
        public bool EnableAttendees { get; set; }
        public bool EnableFloormap { get; set; }
        public bool EnablePhotos { get; set; }
        public bool EnableSponsor { get; set; }
        public bool EnableComments { get; set; }
        public bool EnableGoogleApi { get; set; }
        public bool allow_bookmark { get; set; }
        public string EventImage { get; set; }
        public bool EnableSocialScreen { get; set; }
        public bool EnableSearchScreen { get; set; }
        public string Destination { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string WebURL { get; set; }
        public string QrCodeTitle { get; set; }
        public string AttendeeTitle { get; set; }
        public string FloormapTitle { get; set; }
        public string PhotosTitle { get; set; }
        public string SponsorTitle { get; set; }
        public string MapTitle { get; set; }
        public string SocialTitle { get; set; }
        public string SearchTitle { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public bool EnableSpeaker { get; set; }
        public string SpeakerTitle { get; set; }
        public bool EnableExhibitor { get; set; }
        public string ExhibitorTitle { get; set; }
        public bool EnableVendor { get; set; }
        public string VendorTitle { get; set; }
        public string GoogleFolderID { get; set; }
        public string GoogleAlbumphotoUrl { get; set; }
        public bool OpenUrlInsideorOutsideApp { get; set; }
        public bool AllowTaggingPeopleandLocations { get; set; }
        public bool AllowPhotosBulkDownload { get; set; }
        public bool AutoPushNotLocationChange { get; set; }
        public bool AutoPushNotMinReminder { get; set; }
        public bool AutoPushNotTimeChange { get; set; }
        public string coordinates { get; set; }
        public bool EmailNotesusingAccountEmail { get; set; }
        public bool EmailFavouriteDocumentsusingAccountEmail { get; set; }
        public bool ShowAttendeewithSpeakers { get; set; }
        public bool OpenDocumentsWithinorOutsideURL { get; set; }
        public bool EnableGeneralAgenda { get; set; }
        public bool EnablePersonalAgenda { get; set; }
        public string GeneralAgendaTitle { get; set; }
        public string PersonalAgendaTitle { get; set; }
        public bool EnablePhotoDescription { get; set; }
        public string LocationInfo { get; set; }
        public string LeftMenuLogo { get; set; }
        public bool VendorSortBy { get; set; }
        public bool SponsorSortBy { get; set; }
        public Nullable<int> ScheduledActivityNotificationsTime { get; set; }
        public bool IsSurveyNotificationSent { get; set; }
        public bool EnableSurveys { get; set; }
        public string SurveyTitle { get; set; }
        public bool EnableDocuments { get; set; }
        public string DocumentsTitle { get; set; }
        public bool EnableAnnouncements { get; set; }
        public string AnnouncementsTitle { get; set; }
        public bool EnableEventInfo { get; set; }
        public string EventInfoTitle { get; set; }
        public bool EnableVendorNameSort { get; set; }
        public bool EnableVendorTypeSort { get; set; }
        public bool VendorTypeSortOrder { get; set; }
        public bool EnableSponsorNameSort { get; set; }
        public bool EnableSponsorTypeSort { get; set; }
        public bool SponsorTypeSortOrder { get; set; }
        public bool HideAddPhotos { get; set; }
        public string EventTimeZone { get; set; }
        public string WidgetImage { get; set; }
        public Nullable<double> WidgetImageBoxesZoomPercentage { get; set; }
        public Nullable<double> WidgetImageBoxesOffsetX { get; set; }
        public Nullable<double> WidgetImageBoxesOffsetY { get; set; }
        public bool EnableVendorSurvey { get; set; }
        public bool EnableSponsorSurvey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activite> Activites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendesEvent> AttendesEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatChannel> ChatChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual EventInfo EventInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventLocationDetail> EventLocationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorMapLocation> FloorMapLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorMapping> FloorMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorRegionMapping> FloorRegionMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorRegionMapping> FloorRegionMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupInfo> GroupInfoes { get; set; }
        public virtual ManagerEvent ManagerEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoAlbum> PhotoAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCode> QRCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCode> QRCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialForum> SocialForums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialForum> SocialForums1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SponsorsEvent> SponsorsEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Theme> Themes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WidgetMapping> WidgetMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExhibitorsEvent> ExhibitorsEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorsEvent> VendorsEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveySubmittedFor> SurveySubmittedFors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaiverFormTemplateMapping> WaiverFormTemplateMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventVideo> EventVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventInformation> EventInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userchannel> userchannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserChatChannel> UserChatChannels { get; set; }
    }
}
