//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInfo
    {
        public int ID { get; set; }
        public bool EnableAboutEvent { get; set; }
        public bool EnableAppHelpDesk { get; set; }
        public bool EnableAccomodations { get; set; }
        public bool EnableThingsToKnow { get; set; }
        public bool EnableArrivalInfo { get; set; }
        public string AboutEventIcon { get; set; }
        public string HelpDeskIcon { get; set; }
        public string AccomodationsIcon { get; set; }
        public string ThingsToKnowIcon { get; set; }
        public string ArrivalInfoIcon { get; set; }
        public string AboutEventTitle { get; set; }
        public string AccomodationsTitle { get; set; }
        public string ThingsToKnowTitle { get; set; }
        public string ArrivalInfoTitle { get; set; }
        public string HelpDeskTitle { get; set; }
        public string AboutEventDescription { get; set; }
        public string AccomodationsDescription { get; set; }
        public string ThingsToKnowDescription { get; set; }
        public string ArrivalInfoDescription { get; set; }
        public bool isAboutEventExternalLink { get; set; }
        public bool isHelpDeskExternalLink { get; set; }
        public bool isAccomodationsExternalLink { get; set; }
        public bool isThingsToKnowExternalLink { get; set; }
        public bool isArrivalInformationExternalLink { get; set; }
        public string AboutEventExternalLink { get; set; }
        public string HelpDeskExternalLink { get; set; }
        public string AccomodationsExternalLink { get; set; }
        public string ThingsToKnowExternalLink { get; set; }
        public string ArrivalInformationExternalLink { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
