//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInformation
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<bool> HideSection { get; set; }
        public string AboutSection { get; set; }
        public string IconSection { get; set; }
        public string DescriptionSection { get; set; }
        public Nullable<bool> IsExternalLink { get; set; }
        public string ExternalLinkURL { get; set; }
        public string SectionType { get; set; }
        public Nullable<int> SectionOrder { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
