//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLocationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventLocationDetail()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Coordinates { get; set; }
        public string LocationDescription { get; set; }
        public string Name { get; set; }
        public string MarkerImage1 { get; set; }
        public string MarkerImage2 { get; set; }
        public string Webpageurl { get; set; }
        public string WebPageName { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
    }
}
