//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibitor()
        {
            this.Documents = new HashSet<Document>();
            this.Notes = new HashSet<Note>();
            this.ExhibitorsEvents = new HashSet<ExhibitorsEvent>();
            this.ExhibitorActivities = new HashSet<ExhibitorActivity>();
            this.QRCodes = new HashSet<QRCode>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
        public string DocURL { get; set; }
        public bool Status { get; set; }
        public string Name { get; set; }
        public Nullable<bool> MarkDocumentasFavourite { get; set; }
        public Nullable<bool> SaveShareDocuments { get; set; }
        public Nullable<int> FloorRegionMappingID { get; set; }
        public string TwitterURL { get; set; }
        public string WebsiteURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual FloorRegionMapping FloorRegionMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExhibitorsEvent> ExhibitorsEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExhibitorActivity> ExhibitorActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCode> QRCodes { get; set; }
    }
}
