//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloorRegionMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FloorRegionMapping()
        {
            this.Exhibitors = new HashSet<Exhibitor>();
            this.Sponsors = new HashSet<Sponsor>();
            this.Activites = new HashSet<Activite>();
        }
    
        public int ID { get; set; }
        public int EventID { get; set; }
        public int FMid { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> height { get; set; }
        public string Regioncolor { get; set; }
        public Nullable<int> floorLocationID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Event Event1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exhibitor> Exhibitors { get; set; }
        public virtual FloorMapLocation FloorMapLocation { get; set; }
        public virtual FloorMapping FloorMapping { get; set; }
        public virtual FloorMapping FloorMapping1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sponsor> Sponsors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activite> Activites { get; set; }
    }
}
