//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messaging
    {
        public int ID { get; set; }
        public int SenderID { get; set; }
        public Nullable<int> ReceiverID { get; set; }
        public bool IsGroup { get; set; }
        public Nullable<int> EventGroupID { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Attende Attende { get; set; }
        public virtual Attende Attende1 { get; set; }
    }
}
