//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Activity_id { get; set; }
        public Nullable<int> Vendor_id { get; set; }
        public Nullable<int> Sponsor_id { get; set; }
        public Nullable<int> Exhibitor_id { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> MarkerID { get; set; }
    
        public virtual Activite Activite { get; set; }
        public virtual Attende Attende { get; set; }
        public virtual Exhibitor Exhibitor { get; set; }
        public virtual Sponsor Sponsor { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Event Event { get; set; }
        public virtual EventLocationDetail EventLocationDetail { get; set; }
    }
}
