//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public int UserID { get; set; }
        public string OptionsSelected { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Attende Attende { get; set; }
        public virtual Question Question { get; set; }
    }
}
