//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialForum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SocialForum()
        {
            this.ForumSocialComments = new HashSet<ForumSocialComment>();
            this.ForumSocialComments1 = new HashSet<ForumSocialComment>();
            this.PostUserLikes = new HashSet<PostUserLike>();
            this.PostUserLikes1 = new HashSet<PostUserLike>();
        }
    
        public int ID { get; set; }
        public int EventID { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> UploadON { get; set; }
        public Nullable<int> UploadBY { get; set; }
        public int PostTypeid { get; set; }
        public Nullable<System.DateTime> ApprovedON { get; set; }
        public Nullable<int> ApprovedBY { get; set; }
        public bool Status { get; set; }
        public Nullable<int> TotalLikes { get; set; }
        public int AttendesID { get; set; }
        public Nullable<bool> DeleteRequest { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SocialForumDescription { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Attende Attende { get; set; }
        public virtual Attende Attende1 { get; set; }
        public virtual Event Event { get; set; }
        public virtual Event Event1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumSocialComment> ForumSocialComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumSocialComment> ForumSocialComments1 { get; set; }
        public virtual PostType PostType { get; set; }
        public virtual PostType PostType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostUserLike> PostUserLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostUserLike> PostUserLikes1 { get; set; }
    }
}
