//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsorActivity
    {
        public int ID { get; set; }
        public int SponsorID { get; set; }
        public int ActivityID { get; set; }
    
        public virtual Activite Activite { get; set; }
        public virtual Sponsor Sponsor { get; set; }
    }
}
