//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySubmittedFor
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> SponsorID { get; set; }
    
        public virtual Activite Activite { get; set; }
        public virtual Attende Attende { get; set; }
        public virtual Event Event { get; set; }
        public virtual Question Question { get; set; }
        public virtual Sponsor Sponsor { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
