//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Log
    {
        public int ID { get; set; }
        public string Module { get; set; }
        public string Page { get; set; }
        public string Operation { get; set; }
        public System.DateTime Logdate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Attende Attende { get; set; }
    }
}
