//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateQuestionOption
    {
        public int TQOptionID { get; set; }
        public Nullable<int> TQuestionID { get; set; }
        public string TQOptionText { get; set; }
    
        public virtual TemplateQuestion TemplateQuestion { get; set; }
    }
}
