//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int ID { get; set; }
        public int NotificationID { get; set; }
        public int AttendeeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool Isread { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public bool IsFavourite { get; set; }
    
        public virtual Attende Attende { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
