//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChatChannel
    {
        public long id { get; set; }
        public int userid { get; set; }
        public int channelid { get; set; }
        public int Eventid { get; set; }
        public int unreadmsgcount { get; set; }
        public int deletedmsgid { get; set; }
        public bool isfavorite { get; set; }
        public bool isblocked { get; set; }
        public Nullable<System.DateTime> blockeddate { get; set; }
        public int touserid { get; set; }
        public bool hasleft { get; set; }
        public bool isdeleted { get; set; }
        public Nullable<System.DateTime> hasLeftDate { get; set; }
    
        public virtual channel channel { get; set; }
        public virtual Event Event { get; set; }
    }
}
