//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChannelUnreadCount
    {
        public int id { get; set; }
        public int userid { get; set; }
        public int channelId { get; set; }
        public int unReadMessageCount { get; set; }
    
        public virtual channel channel { get; set; }
    }
}
