//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaiverFormTemplateMapping
    {
        public int ID { get; set; }
        public string FormKey { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> ActivityID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual WaiverFormMappingValue WaiverFormMappingValue { get; set; }
        public virtual Activite Activite { get; set; }
    }
}
