//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DataAccess.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetMapping
    {
        public int ID { get; set; }
        public Nullable<int> WidgetID { get; set; }
        public int XLocation { get; set; }
        public int YLocation { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> EventID { get; set; }
        public bool isExternalLink { get; set; }
        public string ExternalLink { get; set; }
        public string ImagePath { get; set; }
        public int widgetTypeID { get; set; }
        public string Color { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string Justification { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Widget Widget { get; set; }
        public virtual WidgetType WidgetType { get; set; }
    }
}
